const SharedVarConstants = {
    GENERAL_SYS_DOWN_ERR_MSG: "This system is currently not available. Please try again at a later time.",
    BET_TYPE_CD_H2H: "01",
    BET_SELECTION_H2H_HOME: "01",
    BET_SELECTION_H2H_DRAW: "02",
    BET_SELECTION_H2H_AWAY: "03",
    BET_TYPE_H2H_NAME: "1X2",
    DRAW_RESULT: "Draw",
    SETTLED: "Settled",
    NOT_SETTLED: "Not Settled",
    BET_SLIP_MAX_ALLOWED_BET: 5,
    API_SOURCE_COMP_TYPE_EPL: "soccer_epl",
    API_SOURCE_COMP_TYPE_LALIGA: "soccer_spain_la_liga",
    API_SOURCE_COMP_TYPE_BUNDESLIGA: "soccer_germany_bundesliga",
    API_SOURCE_COMP_TYPE_SERIE_A: "soccer_italy_serie_a",
    API_SOURCE_COMP_TYPE_LIGUE_ONE: "soccer_france_ligue_one",
    API_SOURCE_COMP_TYPE_FA_CUP: "soccer_fa_cup",
    API_SOURCE_COMP_TYPE_EFL_CUP: "soccer_efl_cup",
    API_SOURCE_COMP_TYPE_UCL: "soccer_uefa_champs_league",
    COMP_HEADER_EPL: "English Premier League",
    COMP_HEADER_LALIGA: "La Liga",
    COMP_HEADER_BUNDESLIGA: "Bundesliga",
    COMP_HEADER_SERIE_A: "Serie A",
    COMP_HEADER_LIGUE_ONE: "Ligue One",
    COMP_HEADER_FA_CUP: "FA Cup",
    COMP_HEADER_EFL_CUP: "EFL Cup",
    COMP_HEADER_UCL: "UEFA Champions League"
  };

  export default SharedVarConstants;